OCAMLC = ocamlc
OCAMLOPT = ocamlopt
OCAMLDEP = ocamldep
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc

%.cmo: %.ml
	$(OCAMLC) $(OCAMLFLAGS) -c $<

%.cmx: %.ml
	$(OCAMLOPT) $(OCAMLFLAGS) -c $<

%.cmi: %.mli
	$(OCAMLC) $(OCAMLFLAGS) -c $<

%.cma:
	$(OCAMLC) -a $(OCAMLFLAGS) -o $@ $^

%Lex.ml: %.mll
	$(OCAMLLEX) -o "$*Lex.ml" $(OCAMLEX_FLAGS) $<

%Parse.mli %Parse.ml: %.mly
	$(OCAMLYACC) -b "$*Parse" $(OCAMLYACC_FLAGS) $<

Makefile.d: 
	$(OCAMLDEP) $^ > $@
